name: DevDay Github Action
run-name: ${{ github.actor }} - Devday Github Action Test 
on: 
    workflow_dispatch:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.x             
            - name: Restore dependencies
              run: dotnet restore ../../GitHub.Action.DevDays/GitHub.Action.DevDays.csproj
            - name: Build Project
              run: dotnet build ../../GitHub.Action.DevDays/GitHub.Action.DevDays.csproj
            - name: Run Tests
              run: dotnet test ../../GitHub.Action.DevDays/GitHub.Action.DevDays.csproj --no-build --verbosity normal